version: 0.0
os: linux
files:
  - source: /target/*.war
    destination: /var/lib/tomcat/webapps/
  - source: index.html
    destination: /var/lib/tomcat/webapps/web/
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      runas: root
  ApplicationStart:
    - location: scripts/startup_script.sh
    - runas: root
      timeout: 300
