version: 0.0
os: linux
files:
  - source: /target/sparkjava-hello-world-1.0.1.war
    destination: /var/lib/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: /scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
    - runas: root
      timeout: 300
  ApplicationStop:
    - location: /scripts/stop_server
      runas: root
