version: 0.0
os: linux
files:
  - source: /target/
    destination: /var/lib/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: /scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/startup_script.sh
    - runas: root
      timeout: 300
  ApplicationStop:
    - location: /scripts/stop_application.sh
      runas: root
