version: 0.0
os: linux
files:
  - source: /target/*.war
    destination: /var/lib/tomcat/webapps/
  - source: index.html
    destination: /var/lib/tomcat/webapps/web/
hooks:
  ApplicationStart:
    - location: startup_script.sh
      timeout: 300
