version: 0.0
os: linux
files:
  - source: /target/
    destination: /var/lib/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: /scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/startup_script
    - runas: root
      timeout: 300
  ApplicationStop:
    - location: /scripts/stop_application
      runas: root
